name: Self-Evo-123

on:
 # schedule:
  #  - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  self_improvement:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run self-improvement script
        run: |
          python cronbot.py

      - name: Save note2self.json to /todo
        run: |
          TIMESTAMP=$(date +'%y%m%d%H%M')
          mkdir -p /todo
          cp note2self.json /todo/Task_${TIMESTAMP}.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull --rebase
          git add note2self.json .github/workflows/request_payload.json
          git commit -m 'Update note2self.json and request_payload.json'
          git push

      - name: Start new cron job
        run: |
          echo "Starting new cron job to implement the new task"
          # Add logic to start the new cron job based on the saved task
          # Example: echo "* * * * * /path/to/script.sh" | crontab -
